_target_: consistency_policy.teacher_maze.edm_workspace_maze.EDMMazeWorkspace
checkpoint:
  save_last_ckpt: true
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-train_mse_error={train_mse_error:.3f}.ckpt
    k: 2
    mode: min
    monitor_key: train_mse_error
dataloader:
  batch_size: 1024
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 2
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 128
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: dp_test
  project: diffusion_policy_debug
  resume: false
  tags:
  - train_diffusion_unet_maze_small
  - maze2d_small
  - default
multi_run:
  run_dir: data/outputs/2022.12.29/22.31.27_train_diffusion_unet_hybrid_square_image
  wandb_name_base: dp_test
n_action_steps: 128
n_latency_steps: 0
n_obs_steps: 2
name: train_diffusion_unet_maze_small
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-04
past_action_visible: false
policy:
  _target_: consistency_policy.teacher_maze.edm_policy_maze.KarrasUnetHybridMazePolicy
  inference_mode: none # this will be populated automatically from training.inference_mode, do not set it here
  cond_predict_scale: true
  diffusion_step_embed_dim: 256
  down_dims:
  - 256
  - 512
  - 1024
  horizon: 128
  kernel_size: 5
  n_action_steps: 128
  n_groups: 8
  n_obs_steps: 2
  delta: -1
  noise_scheduler:
    _target_: consistency_policy.diffusion.Karras_Scheduler
    time_min: 0.02
    time_max: 80.0
    rho: 7.0
    bins: 80
    solver: heun
    time_sampler: log_normal
    scaling: boundary
    use_c_in: true
    data_std: .5
    clamp: true
    name: heun80
  obs_as_global_cond: true
  shape_meta:
    action:
      shape:
      - 2
    observation:
      shape: 
      - 4
shape_meta:
    action:
      shape:
      - 2
    observation:
      shape: 
      - 4
task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.d4rl_dataset.D4RLDataset
    env_name: 'maze2d-umaze-v1'
    horizon: 128
    pad_after: 0
    pad_before: 0
    seed: 42
    val_ratio: 0.02
  env_runner:
    _target_: diffusion_policy.env_runner.maze2d_lowdim_state_runner.Maze2dLowdimStateRunner
    env_name: 'maze2d-umaze-v1'
    crf: 22
    fps: 10
    max_steps: 1000
    n_action_steps: 128
    n_envs: 1
    n_obs_steps: 2
    n_test: 20
    n_test_vis: 16
    n_train: 2
    n_train_vis: 2
    past_action: false
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
  name: d4rl_maze_small
  shape_meta:
    action:
      shape:
      - 2
    observation:
      shape: 
      - 4
  task_name: d4rl_maze_small
task_name: d4rl_maze_small
training:
  inference_mode: false # Setting this to true disables the teacher, warm start, and training loop
  online_rollouts: true # Setting this to false disables the env_runner
  checkpoint_every: 20
  debug: false
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 400
  resume: false
  resume_path: None
  rollout_every: 25
  sample_every: 10
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
  val_sample_every: 5
  output_dir: ??? ## path to output directory
val_dataloader:
  batch_size: 1024
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false


## large: 384  medium: 256  umaze: 128