_target_: consistency_policy.reward_guided_student_d4rl.guided_ctm_workspace_d4rl.GuidedCTMWorkspaceD4RL
checkpoint:
  save_last_ckpt: false
  save_last_snapshot: false
  topk:
    format_str: epoch={epoch:04d}-test_mean_scores={test_mean_scores:.3f}.ckpt
    k: 5
    mode: max
    monitor_key: test_mean_scores
dataloader:
  batch_size: 4800
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: true
dataset_obs_steps: 4
ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  inv_gamma: 1.0
  max_value: 0.9999
  min_value: 0.0
  power: 0.75
  update_after_step: 0
exp_name: default
horizon: 16
keypoint_visible_rate: 1.0
logging:
  group: null
  id: null
  mode: online
  name: default
  project: cm_policy_debug
  resume: false
multi_run:
  run_dir: data/outputs/cd/square/ctmpp
  wandb_name_base: dsm_test
n_action_steps: 1
n_latency_steps: 0
n_obs_steps: 1
name: train_diffusion_unet_hybrid
obs_as_global_cond: true
optimizer:
  _target_: torch.optim.AdamW
  betas:
  - 0.95
  - 0.999
  eps: 1.0e-08
  lr: 0.0001
  weight_decay: 1.0e-04
past_action_visible: false
policy:
  _target_: consistency_policy.reward_guided_student_d4rl.guided_ctm_policy_d4rl.GuidedCTMPUnetD4RLPolicy
  inference_mode: none # this will be populated automatically from training.inference_mode, do not set it here
  cond_predict_scale: true
  diffusion_step_embed_dim: 128
  down_dims:
  - 512
  - 1024
  - 2048
  reward_step_embed_dim: 32
  reward_down_dims:
  - 64
  - 128
  - 256
  dropout_rate: 0.2
  horizon: 16
  kernel_size: 5
  n_action_steps: 1
  n_groups: 8
  n_obs_steps: 1
  #extra args
  initial_ema_decay: 0.0
  delta: -1 
  special_skip: true
  chaining_times: ['D', 27, 54]
  #teacher
  teacher_path: ??? ## path to teacher ckpt
  #reward
  reward_path: ??? ## path to reward ckpt
  #KDE
  use_kde: False
  kde_samples: 0
  #warm start
  edm: ??? ## path to teacher ckpt
  losses: [["ctm", "dsm", "rwd"], [1, 1, 0.4]]
  ctm_sampler: ctm
  dsm_weights: "karras"
  noise_scheduler:
    _target_: consistency_policy.diffusion.CTM_Scheduler
    time_min: 0.02
    time_max: 80.0
    rho: 7.0
    bins: 80
    solver: heun
    scaling: boundary
    use_c_in: true
    data_std: .5
    time_sampler: ctm
    clamp: true
    ode_steps_max: 1
  obs_as_global_cond: true
  shape_meta:
    action:
      shape:
      - 6
    observation:
      shape: 
      - 17
shape_meta:
    action:
      shape:
      - 6
    observation:
      shape: 
      - 17
task:
  abs_action: true
  dataset:
    _target_: diffusion_policy.dataset.d4rl_dataset.D4RLDataset
    env_name: 'walker2d-medium-v2'
    horizon: 16
    pad_after: 0
    pad_before: 0
    seed: 42
    val_ratio: 0.0
  env_runner:
    _target_: diffusion_policy.env_runner.d4rl_lowdim_runner.D4RLLowdimRunner
    env_name: 'walker2d-medium-v2'
    crf: 22
    fps: 80
    max_steps: 1000
    n_action_steps: 1
    n_envs: 1
    n_obs_steps: 1
    n_test: 20
    n_test_vis: 16
    n_train: 2
    n_train_vis: 2
    past_action: false
    test_start_seed: 100000
    tqdm_interval_sec: 1.0
  name: d4rl_walker_medium
  shape_meta:
    action:
      shape:
      - 6
    observation:
      shape: 
      - 17
  task_name: d4rl_walker_medium
task_name: d4rl_walker_medium
training:
  inference_mode: false # Setting this to true disables the teacher, warm start, and training loop
  online_rollouts: true # Setting this to false disables the env_runner
  debug: false
  checkpoint_every: 10
  device: cuda:0
  gradient_accumulate_every: 1
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_train_steps: null
  max_val_steps: null
  num_epochs: 700
  resume: false
  resume_path: ???
  rollout_every: 10
  sample_every: 10
  seed: 42
  tqdm_interval_sec: 1.0
  use_ema: true
  val_every: 1
  val_sample_every: 5
  output_dir: ??? ## path to output directory
  val_chaining_steps: 1
  p_epochs: 700
val_dataloader:
  batch_size: 1024
  num_workers: 8
  persistent_workers: false
  pin_memory: true
  shuffle: false